apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-4
  template:
    metadata:
      labels:
        app: superexec-clientapp-4
    spec:
      containers:
      - name: superexec-clientapp
        # TODO Sobald wir in google Cloud ein Projekt haben und alles konfiguiert  <YOUR_PROJECT_ID> mit den project identifier ersetzen
        image: us-central1-docker.pkg.dev/<YOUR_PROJECT_ID>/flower-gcp-example-artifacts/quickstart_numpy_superexec:0.0.1
        args:
          - "--insecure"
          - "--appio-api-address"
          - "supernode-4-service:9094"
          - "--plugin-type"
          - "clientapp"