apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-serverapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-serverapp
  template:
    metadata:
      labels:
        app: superexec-serverapp
    spec:
      containers:
      - name: superexec-serverapp
        # TODO Sobald wir in google Cloud ein Projekt haben und alles konfiguiert  <YOUR_PROJECT_ID> mit den project identifier ersetzen
        image: us-central1-docker.pkg.dev/<YOUR_PROJECT_ID>/flower-gcp-example-artifacts/quickstart_numpy_superexec:0.0.1
        args:
          - "--insecure"
          - "--appio-api-address"
          - "superlink-service:9091"
          - "--plugin-type"
          - "serverapp"