apiVersion: apps/v1
kind: Deployment
metadata:
  name: supernode-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supernode-4
  template:
    metadata:
      labels:
        app: supernode-4
    spec:
      containers:
      - name: supernode
        image: flwr/supernode:1.33.0
        args:
          - "--insecure"
          - "--superlink"
          - "superlink-service:9092"
          - "--clientappio-api-address"
          - "0.0.0.0:9094"
          - "--isolation"
          - "process"
        ports:
        - containerPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: supernode-4-service
spec:
  selector:
    app: supernode-4
  ports:
  - protocol: TCP
    port: 9094
    targetPort: 9094