apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-clientapp-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-clientapp-4
  template:
    metadata:
      labels:
        app: superexec-clientapp-4
    spec:
      containers:
      - name: superexec-clientapp
        image: us-central1-docker.pkg.dev/fml-handwriting-2026/flower-gcp-example-artifacts/handwriting-superexec:0.0.1
        args:
          - "--insecure"
          - "--appio-api-address"
          - "supernode-4-service:9094"
          - "--plugin-type"
          - "clientapp"