apiVersion: apps/v1
kind: Deployment
metadata:
  name: superexec-serverapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superexec-serverapp
  template:
    metadata:
      labels:
        app: superexec-serverapp
    spec:
      containers:
      - name: superexec-serverapp
        image: us-central1-docker.pkg.dev/fml-handwriting-2026/flower-gcp-example-artifacts/handwriting-superexec:0.0.1
        args:
          - "--insecure"
          - "--appio-api-address"
          - "superlink-service:9091"
          - "--plugin-type"
          - "serverapp"